class Light:
    ON = "on"
    OFF = "off"
    TOGGLE = "toggle"
    RELEASE = "release"
    ON_FULL_BRIGHTNESS = "on_full_brightness"
    ON_FULL_COLOR_TEMP = "on_full_color_temp"
    CLICK_BRIGHTNESS_UP = "click_brightness_up"
    CLICK_BRIGHTNESS_DOWN = "click_brightness_down"
    CLICK_BRIGHTNESS_TOGGLE = "click_brightness_toggle"
    CLICK_COLOR_UP = "click_color_up"
    CLICK_COLOR_DOWN = "click_color_down"
    CLICK_COLOR_TOGGLE = "click_color_toggle"
    CLICK_COLOR_TEMP_UP = "click_color_temp_up"
    CLICK_COLOR_TEMP_DOWN = "click_color_temp_down"
    CLICK_COLOR_TEMP_TOGGLE = "click_color_temp_toggle"
    CLICK_XY_COLOR_UP = "click_xy_color_up"
    CLICK_XY_COLOR_DOWN = "click_xy_color_down"
    CLICK_XY_COLOR_TOGGLE = "click_xy_color_toggle"
    HOLD_BRIGHTNESS_UP = "hold_brightness_up"
    HOLD_BRIGHTNESS_DOWN = "hold_brightness_down"
    HOLD_BRIGHTNESS_TOGGLE = "hold_brightness_toggle"
    HOLD_COLOR_UP = "hold_color_up"
    HOLD_COLOR_DOWN = "hold_color_down"
    HOLD_COLOR_TOGGLE = "hold_color_toggle"
    HOLD_COLOR_TEMP_UP = "hold_color_temp_up"
    HOLD_COLOR_TEMP_DOWN = "hold_color_temp_down"
    HOLD_COLOR_TEMP_TOGGLE = "hold_color_temp_toggle"
    HOLD_XY_COLOR_UP = "hold_xy_color_up"
    HOLD_XY_COLOR_DOWN = "hold_xy_color_down"
    HOLD_XY_COLOR_TOGGLE = "hold_xy_color_toggle"


class MediaPlayer:
    HOLD_DOWN = "hold_down"
    HOLD_UP = "hold_up"
    VOLUME_DOWN = "volume_down"
    VOLUME_UP = "volume_up"
    RELEASE = "release"
    PLAY_PAUSE = "play_pause"
    NEXT_TRACK = "next_track"
    PREVIOUS_TRACK = "previous_track"
