name: Update copyright year(s) in license file

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 1 *

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
